### ISSUE TITLE
addArchRGenome-How to creat a personal genome, like rice plant genome?

### ISSUE THREAD

**Issue by yaojiayingJenny** [GreenleafLab/ArchR_2020#1]

**Comment by yaojiayingJenny** [comment]
Could we build a genome by using .fa and gtf files ? The addArchRGenome function need a valid BSgenome!

**Comment by rcorces** [comment]
ArchR currently requires genomes in a very particular format as described here - https://www.archrproject.com/bookdown/getting-set-up.html
If your system does not have the required genome objects already, you would have to make those objects in the correct format and we dont provide support for doing that. If you have questions about those objects and other packages, we encourage you to use other forums to find those answers.
