### ISSUE TITLE
Large Hematopoiesis Shared files not longer available

### ISSUE THREAD

**Issue by vimarin** [GreenleafLab/ArchR_2020#6]
Hello,
In the ArchR_2020 page, the shared files "Large Hematopoiesis" in the "Additional Data Download Links" are not longer available.
Might it be possible to rshare them again, please ?
In particular, it will be very useful to have access to "ArchR Project Containing Arrow Files".

Thanks a lot for this impressive project and for your help and your work developing and sharing this project and data.
Viviana

**Comment by xiachenrui** [comment]
We find the same problem, could you please reply it?

**Comment by rcorces** [comment]
Sorry for the delay. I'll work on finding these files. They seem to have been deleted from a shared google drive.

**Comment by vimarin** [comment]
Thanks a lot Ryan for tour precious time.
Viviana
----- Mail d’origine -----
De: Ryan Corces ***@***.***>
À: GreenleafLab/ArchR_2020 ***@***.***>
Cc: vimarin ***@***.***>, Author ***@***.***>
Envoyé: Mon, 12 Jul 2021 17:17:18 +0200 (CEST)
Objet: Re: [GreenleafLab/ArchR_2020] Large Hematopoiesis Shared files not longer available (#6)

Sorry for the delay. I'll work on finding these files. They seem to have been deleted from a shared google drive.

**Comment by fl-yu** [comment]
We are still enthusiastic waiting for access to this dataset. Thanks

**Comment by rcorces** [comment]
Apologies for how long this has taken. These files have now been made publicly available at new links which are now reflected on the ArchR_2020 page -
https://github.com/GreenleafLab/ArchR_2020

As these files are rather large, I've added md5sums for you to check. Please let me know if you encounter issues downloading the files. I'm closing this for now but feel free to comment again here.

**Comment by fl-yu** [comment]
Thank you for sharing the data! I have a question that how could I get the cell-type specific pseudo-bulk bigwig files for the integrated large heme dataset?

**Comment by rcorces** [comment]
from the tar archive, these are in a folder called "GroupCoverages" though they are in HDF5 format. you can create bigwig files from the project using `getGroupBW()`
