### ISSUE TITLE
no bam file for Buenrostro et al 2018

### ISSUE THREAD

**Issue by fl-yu** [GreenleafLab/ArchR_2020#8]
Hi, I did not find the bam file from the provided link
` Buenrostro et al 2018 (Bam Files) - https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96772`
Is there any chance that I could get the bam file you used and update the link? Thank you!

**Comment by rcorces** [comment]
Sorry for the confusion. the "(Bam Files)" implies that we used BAM files as input to ArchR. Not that we downloaded BAM files. You will have to align the data yourself.
