### ISSUE TITLE
Differences between ArchR and Signac

### ISSUE THREAD

**Issue by cv55** [GreenleafLab/ArchR_2020#9]
Hello,
i just started using ArchR as a more versatile alternative of Signac, and I noticed a few differences when analysing the same dataset. First the number of cells ArchR retrieved from the fragments file (output from cellranger atac) was much higher compared to the number of cells called from cellranger.
Second, the TSS estimation was higher when using ArchR (for some cells the TSS enrichment score estimated from ArchR was 3 times higher that the TSS score from Signac). I am using the same reference hg38, following the commands shown in the respective tutorials.
Is it something you have also observed?

Thanks,
Christos

**Comment by rcorces** [comment]
This is not an issue and should be posted to Discussions. Moving it there but please post to the correct place in the future.

**Comment by rcorces** [comment]
Sorry - didnt realize what repository this was posted in. Please post in the Discussion sections of ArchR. This repository is strictly for the publication, not the ArchR software itself.
https://github.com/GreenleafLab/ArchR/discussions
